name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repos README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # FORZAMOS QUE MIRE TUS COMMITS Y ESTRELLAS
          GH_USERNAME: Rabenn
          COMMIT_MSG: "⚡ Actualizada actividad reciente"
          MAX_LINES: 10
          # AQUÍ ESTÁ EL TRUCO: Añadimos PushEvent (commits) y WatchEvent (estrellas)
          FILTER_EVENTS: "PushEvent,PullRequestEvent,IssuesEvent,IssueCommentEvent,WatchEvent"
